[project]
name = "mtm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fire>=0.7.0",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "transformers>=4.51.1",
]
